### PR TITLE
Fix a number of signficiant bugs

### LINKED ISSUE #2116: [BUG] Crash after reaching certain altitude
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
its called AdvancedRocketry-1.16.5-2.0.0-12-universal so i assume its version 2.0.0

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
Yes

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!]

## Does this occur without other mods installed
Yes, and no. Ive tried both
>If Y, what is the MINIMUM set of mods required.
like 90, so i guess this is impossible to fix, without not doing extensive research
>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/3X58fBVa 

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

[crash-2021-05-11_22.43.52-server.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6463699/crash-2021-05-11_22.43.52-server.txt)
^^ This is the crash report, probably the same as the one above.

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

### LINKED ISSUE #2200: [BUG] Advancement names not showing up properly
## Version of Advanced Rocketry
1.16.5-2.0.0-16

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
1.16.5-1.0.2-26

## Version of Minecraft
1.16.5 (Forge 36.2.2)

## Does this occur without other mods installed
Yes

## Description of the problem
Get any advancement (such as getting the holoprojector), the advancement in chat shows the advancement ID, not its name.
image

### LINKED ISSUE #2201: [BUG] Bipropellant rocket parts untextured
## Version of Advanced Rocketry
1.16.5-2.0.0-16

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
1.16.5-1.0.2-26

## Version of Minecraft
1.16.5 (Forge 36.2.2)

## Does this occur without other mods installed
Yes

## Description of the problem
Bipropellant rocket motors and fuel tanks are untextured, and have a block ID name rather than an actual block name
image
image

### PR DESCRIPTION
**Pull request by voidsong-dragonfly**

### CODE REVIEW

File: src/main/java/zmaster587/advancedRocketry/client/render/planet/RenderPlanetarySky.java [hunk 1]
```diff
@@ -343,9 +340,10 @@ public void render(MatrixStack matrix, float partialTicks) {
 		float f6;
 
 		//Simulate atmospheric thickness
-		f1 *= atmosphere;
-		f2 *= atmosphere;
-		f3 *= atmosphere;
+		f1 = properties.getAtmosphereDensity() < 1 ? 0 : (float) Math.pow(f1, Math.sqrt(Math.max(atmosphere, 0.81)));
```
Comment (zmaster587) [inline src/main/java/zmaster587/advancedRocketry/client/render/planet/RenderPlanetarySky.java]: Could we set `properties.getAtmosphereDensity()` to a variable like we do `atmosphere` once to avoid calling it 3x?

If we're using absolute atmoshperic density here it might be good to rename `atmosphere` to `atmosphereAtHeight` or something and create a new `atmosphere` variable

File: src/main/java/zmaster587/advancedRocketry/client/render/planet/RenderPlanetarySky.java [hunk 2]
```diff
@@ -475,13 +471,12 @@ public void render(MatrixStack matrix, float partialTicks) {
 
 
 		RenderSystem.disableTexture();
-		float f18 = mc.world.getStarBrightness(partialTicks) * f6 * (atmosphere) + (1-atmosphere);
+		float f18 = mc.world.getStarBrightness(partialTicks) * f6 + ((atmosphere == 0 || (f1 < 0.09 && f2 < 0.09 && f3 < 0.09)) ? 1 : 0) - (atmosphere > 1 ? atmosphere - 1 : 0);
```
Comment (zmaster587) [inline src/main/java/zmaster587/advancedRocketry/client/render/planet/RenderPlanetarySky.java:477]: Would it be possible to get a comment briefly describing what's going on here?

File: src/main/java/zmaster587/advancedRocketry/client/render/planet/RenderPlanetarySky.java [hunk 3]
```diff
@@ -543,113 +538,139 @@ public void render(MatrixStack matrix, float partialTicks) {
...
+				//Close enough approximation, I missed something but seems to off by no more than 30*
+				//Nobody will look
+				float phiAngle = (float) ((moons.orbitalPhi) * Math.PI / 180f);
+				double x = -MathHelper.sin(phiAngle) * MathHelper.cos((float) moons.orbitTheta);
+				double y = MathHelper.sin((float) moons.orbitTheta);
+				double rotation = (-Math.PI / 2f + Math.atan2(x, y) - (moons.orbitTheta - Math.PI) * MathHelper.sin(phiAngle)) + Math.PI;
+
+				//This is for non-sunset stuff
+				float alpha2 = atmosphere >= 2 ? 0 : 1;
+				//Color sunset planets in the sunset zone by fog and atmosphere color
```
Comment (zmaster587) [inline src/main/java/zmaster587/advancedRocketry/client/render/planet/RenderPlanetarySky.java:657]: Magic: the mathening

**Review by zmaster587 — CHANGES_REQUESTED** [review]
Really good stuff!
Though for clenliness/ease of changing later I do think we should make a variable for planet atmosphere density

**Review by zmaster587 — APPROVED** [review]
